# -*- coding: utf-8 -*-
"""automobilepreipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/112VNrlMwtMD0S9ThvWF1rztauYTcWn_n
"""

import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

df2 = pd.read_csv("automobile_price_dataset.csv")

print(df2.info())
print(df2.describe())
print(df2.isnull().sum())

df2.hist(bins=20, figsize=(12, 8))
plt.suptitle("Numeric Feature Distributions", fontsize=16)
plt.show()

categorical_cols = ['Brand', 'Fuel_Type', 'Transmission']
for col in categorical_cols:
    plt.figure(figsize=(10, 5))
    sns.countplot(data=df2, x=col, order=df2[col].value_counts().index)
    plt.title(f"{col} Distribution")
    plt.xticks(rotation=45)
    plt.show()

plt.figure(figsize=(8, 5))
sns.scatterplot(data=df2, x='Year', y='Price')
plt.title("Price vs Year")
plt.show()

plt.figure(figsize=(8, 5))
sns.scatterplot(data=df2, x='Mileage', y='Price')
plt.title("Price vs Mileage")
plt.show()

plt.figure(figsize=(8, 5))
sns.scatterplot(data=df2, x='Engine_Size', y='Price')
plt.title("Price vs Engine Size")
plt.show()

sns.boxplot(data=df2, x='Fuel_Type', y='Price')
plt.title("Price by Fuel Type")
plt.show()

sns.boxplot(data=df2, x='Transmission', y='Price')
plt.title("Price by Transmission")
plt.show()

top_brands_price = df2.groupby('Brand')['Price'].mean().sort_values(ascending=False).head(10)
top_brands_count = df2['Brand'].value_counts().head(10)

plt.figure(figsize=(10,5))
sns.barplot(x=top_brands_price.index, y=top_brands_price.values)
plt.title("Top 10 Brands by Average Price")
plt.xticks(rotation=45)
plt.show()

plt.figure(figsize=(10,5))
sns.barplot(x=top_brands_count.index, y=top_brands_count.values)
plt.title("Top 10 Brands by Count")
plt.xticks(rotation=45)
plt.show()

